CREATE TABLE IF NOT EXISTS `USER`
(
    `USER_ID`    INT NOT NULL AUTO_INCREMENT COMMENT '사용자ID',
    `USER_EMAIL`    VARCHAR(100) NOT NULL COMMENT '사용자이메일',
    `USER_PW`    VARCHAR(255) NOT NULL COMMENT '비밀번호',
    `USER_NICKNAME`    VARCHAR(30) NOT NULL COMMENT '닉네임',
    `USER_NAME`    VARCHAR(255) NOT NULL COMMENT '이름',
    `USER_GENDER`    CHAR(1) NOT NULL COMMENT '성별',
    CHECK (USER_GENDER IN ('M', 'F')),
    `USER_BIRTH`    DATE NOT NULL COMMENT '생년월일',
    `USER_PHONE`    VARCHAR(13) NOT NULL COMMENT '휴대폰번호',
    CHECK (USER_PHONE REGEXP '^0[0-9]{2}-[0-9]{3,4}-[0-9]{4}$' OR USER_PHONE REGEXP '^0[0-9]{9,10}$'),
    `USER_AUTH`    BOOLEAN NOT NULL DEFAULT '1' COMMENT '권한',
    `IS_NOTIFIED`    BOOLEAN DEFAULT '1' NOT NULL COMMENT '알림수신여부',
    `IS_ACTIVE`    BOOLEAN DEFAULT '1' NOT NULL COMMENT '탈퇴여부',
 PRIMARY KEY ( `USER_ID` )
) COMMENT = '사용자';